name: Discord-MCPE
author: Niekert
version: "2.0.0-ALPHA7-14"
api:
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
- 3.0.0-ALPHA11
- 3.0.0-ALPHA12
- 3.0.0-ALPHA13
- 3.0.0-ALPHA14
main: Niekert\DiscordMCPE\Main

commands:
    discord:
        description: Send an message to Discord!
        permission: discord.send
        usage: /discord MESSAGE
        aliases: [dc]

permissions:
    discord.send:
        default: true
